[package]
name = "hello"
version = "0.1.0"
description = "A HASAB default project"
repository = "https://packages.hasab.org"

[project]
source = "src"
tests = "tests"
entry = "main"
output = "build"
jvm_target = "21"
