package hasab.runtime.internal

import hasab.runtime.exceptions.*
import java.io.PrintWriter
import java.io.StringWriter

/**
 * Internal runtime helpers used by the HASAB compiler-generated bytecode.
 *
 * Methods in this object are `@PublishedApi internal` so they are accessible
 * from inline functions but should not be called from user code directly.
 */
public object HsInternal {

    /**
     * Asserts that [value] is not null and returns it.
     *
     * @throws HsNullPointerException if [value] is `null`.
     */
    @PublishedApi
    internal fun checkNotNull(value: Any?): Any {
        return value ?: nullReference()
    }

    /**
     * Asserts that [value] is assignable to [expectedType] and returns it.
     *
     * @throws HsTypeException if [value] is not of the expected type.
     */
    @PublishedApi
    internal fun checkType(value: Any?, expectedType: String): Any? {
        if (value == null) return null
        val actualType = value::class.simpleName ?: value::class.java.simpleName
        if (!isAssignable(value, expectedType)) {
            typeMismatch(expectedType, actualType)
        }
        return value
    }

    /**
     * Throws an [HsTypeException] indicating a mismatch between [expected] and [actual] types.
     */
    @PublishedApi
    internal fun typeMismatch(expected: String, actual: String): Nothing {
        throw HsTypeException.create(expected, actual)
    }

    /**
     * Throws an [HsIndexOutOfBoundsException] for the given [index] and [size].
     */
    @PublishedApi
    internal fun indexOutOfBounds(index: Int, size: Int): Nothing {
        throw HsIndexOutOfBoundsException("Index $index out of bounds for size $size")
    }

    /**
     * Throws an [HsNullPointerException] for a null dereference.
     */
    @PublishedApi
    internal fun nullReference(): Nothing {
        throw HsNullPointerException("Null reference dereference")
    }

    /**
     * Throws an [HsDivisionByZeroError].
     */
    @PublishedApi
    internal fun divisionByZero(): Nothing {
        throw HsDivisionByZeroError("Division by zero")
    }

    /**
     * Throws an [HsStackOverflowError].
     */
    @PublishedApi
    internal fun stackOverflow(): Nothing {
        throw HsStackOverflowError("Stack overflow")
    }

    /**
     * Throws an [HsNotImplementedError] for the given [feature].
     */
    @PublishedApi
    internal fun notImplemented(feature: String): Nothing {
        throw HsNotImplementedError("Not implemented: $feature")
    }

    /**
     * Throws an [HsValueError] with the given [message].
     */
    @PublishedApi
    internal fun valueError(message: String): Nothing {
        throw HsValueError(message)
    }

    /**
     * Throws an [HsRuntimeException] with the given [message].
     */
    @PublishedApi
    internal fun runtimeError(message: String): Nothing {
        throw HsRuntimeException(message)
    }

    /**
     * Throws an [HsIOError] with the given [message] and optional [cause].
     */
    @PublishedApi
    internal fun ioError(message: String, cause: Throwable? = null): Nothing {
        throw HsIOError(message, cause)
    }

    /**
     * Formats a human-readable stack trace string from [throwable].
     */
    @PublishedApi
    internal fun formatStacktrace(throwable: Throwable): String {
        val sw = StringWriter()
        throwable.printStackTrace(PrintWriter(sw))
        return sw.toString()
    }

    /**
     * Returns a safe string representation of [obj], returning `"<null>"` for null values.
     */
    @PublishedApi
    internal fun safeToString(obj: Any?): String = obj?.toString() ?: "<null>"

    private fun isAssignable(value: Any, expectedType: String): Boolean {
        return when (expectedType) {
            "Int", "int" -> value is Int
            "Long", "long" -> value is Long
            "Float", "float" -> value is Float
            "Double", "double" -> value is Double
            "Boolean", "boolean" -> value is Boolean
            "String" -> value is String
            "Char", "char" -> value is Char
            "Byte", "byte" -> value is Byte
            "Short", "short" -> value is Short
            else -> true
        }
    }
}
