/**
 * JVM bytecode backend for the HASAB programming language.
 *
 * This package contains the components for translating HASAB's
 * High-Level Intermediate Representation (HIR) into JVM `.class` files.
 *
 * ## Architecture
 *
 * The backend follows a layered architecture:
 *
 * ```
 * JvmBackend (orchestrator)
 *   └─> BytecodeGenerator (per-function)
 *         └─> JvmInstructionEmitter (per-instruction)
 *               └─> MethodBuilder / ClassBuilder (ASM wrappers)
 * ```
 *
 * ### Key Components
 *
 * - [JvmBackend] — Top-level entry point. Takes a [hasab.compiler.hir.cfg.HirCfgModule]
 *   and produces `.class` file byte arrays.
 * - [ClassBuilder] — Wraps ASM's `ClassWriter` to construct JVM class files.
 * - [MethodBuilder] — Wraps ASM's `MethodVisitor` for method-level bytecode emission.
 * - [JvmInstructionEmitter] — Translates individual HIR CFG instructions into JVM bytecode.
 * - [BytecodeGenerator] — Orchestrates per-function code generation.
 * - [JvmTypeMapper] — Maps HASAB types to JVM type descriptors and opcodes.
 * - [LocalVariableManager] — Maps HASAB virtual registers to JVM local variable slots.
 * - [StackFrameAnalyzer] — Computes JVM stack map frame types.
 * - [BytecodeValidator] — Validates generated bytecode using ASM's `CheckClassAdapter`.
 * - [DebugInfoBuilder] — Generates source-level debug information (line numbers, variables).
 * - [ConstantPoolBuilder] — Tracks and deduplicates string constants.
 *
 * ## Usage
 *
 * ```kotlin
 * val backend = JvmBackend(JvmBackendConfig(className = "MyProgram"))
 * val result = backend.compile(cfgModule)
 * if (result.success) {
 *     backend.writeClasses(result, File("build/classes"))
 * }
 * ```
 *
 * ## Type Mapping
 *
 * | HASAB Type | JVM Descriptor | JVM Type |
 * |-----------|---------------|----------|
 * | `int`     | `I`           | `int`    |
 * | `float`   | `F`           | `float`  |
 * | `bool`    | `Z`           | `boolean`|
 * | `char`    | `C`           | `char`   |
 * | `string`  | `Ljava/lang/String;` | `String` |
 * | `void`    | `V`           | `void`   |
 * | `[T]`     | `[T_desc`    | `T[]`    |
 * | `struct`  | `Lname;`     | `name` class |
 * | `enum`    | `Lname;`     | `name` enum class |
 */
package hasab.compiler.backend.jvm
